fragment UserTimelineTweetFields on TweetType
{
     possibly_sensitive
    created_at
    author_id
    lang
    reply_settings
    id
    public_metrics
    {
        tweet_count
        followers_count
        following_count
        listed_count
        }
            source
            text
            entities
            {
                mentions
            {
                start
                end
                username
                id
                }
                 urls
                {
                start
                end
                url
                expanded_url
                display_url
                images 
                    {
                    url
                    width
                    height
                 }
                    status
                    title
                    description
                    unwound_url
                }
            }
            __typename
            conversation_id
            includes
            {
                media
                {
                    width
                    height
                    media_key
                    url
                    type
                }
            }
}